# -*- coding: utf-8 -*-
"""Latihan1 - modul2 - Cristina.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KJe0fFqt4dxf5NH_dtEgYn-dxTLQYMto
"""

import time
import numpy as np

size_of_vec = 1000000

def pure_python_version():
  t1 = time.time()
  X = range(size_of_vec)
  Y = range(size_of_vec)
  Z = [X[i] + Y[i] for i in range(len(X))]
  return time.time() - t1

def numpy_version():
  t1 = time.time()
  X = np.arange(size_of_vec)
  Y = np.arange(size_of_vec)
  Z = X+Y
  return time.time() - t1

t1 = pure_python_version()
t2 = numpy_version()

t1 = pure_python_version()
t2 = numpy_version()

print(f'''Waktu running pure pythong adalah {round(t1,4)} detik.
Waktu running versi numpy adalah {round(t2,4)} detik.
Numpy di contoh ini {(round((t1/t2),4))} kali lebih cepat!''' )

#1D Array

my_list = [1,2,3]
print(my_list)

print(np.array(my_list))

#2D Array
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)

print(np.array(my_matrix))

#3D Array

my_list3 = [
            [[1,2,3],[4,5,6],[7,8,9]],
            [[10,11,12],[13,14,15],[16,17,18]],
            [[19,20,21],[22,23,24],[25,26,27]]
]
print(np.array(my_list3))

#Create Numpy Arrays arange

np.arange(0,10) #Start (0 by default), Stop

np.arange(0,11,2) #Start, Stop, Step

#Creating Numpy Arrays zeros and ones

np.zeros(3)

np.zeros((5,5))

np.ones(3)

np.ones((3,3))

#Creating Numpy Arrays eye

np.eye(4)

#Creating Numpy Arrays linspace

np.linspace(0,10,3)

np.linspace(0,10,50)

#Creating Numpy Arrays random.rand

np.random.rand(2)

np.random.rand(5,5)

#Creating Numpy Arrays random.randn

np.random.randn(2)

np.random.randn(5,5)

#Creating Numpy Arrays random.randint

np.random.randint(1,100)

np.random.randint(1,100,10)

#Array Attributes and Methods - Shape

my_list = [1,2,3]
array_1d = np.array(my_list)

my_list2 = [[1,2,3],[4,5,3],[7,8,9]]
array_2d = np.array(my_list2)

my_list3 = [
            [[1,2,3],[4,5,3],[7,8,9]],
            [[10,11,12],[13,14,15],[16,17,18]],
            [[19,20,21],[22,23,24],[25,26,27]]
]
array_3d = np.array(my_list3)

array_1d.shape

array_2d.shape

array_3d.shape

#Array Attributes and Methods - reshape

np.array(my_list)

arr = np.arange(0,25)
print(arr)

arr.shape

arr.reshape(1,25)

arr.reshape(1,25).shape

arr.reshape(5,5)

arr.reshape(25,1)

arr.reshape(25,1).shape

array_2d.reshape(-1)

array_2d.reshape(-1).shape

array_3d.reshape(-1)

array_3d.reshape(-1).shape

ranarr = np.random.randint(0,40,10)
print(ranarr)

ranarr.max()

ranarr.argmax()

ranarr.min()

ranarr.argmin()

arr.dtype

arr1 = np.linspace(0,10,10)
arr1.dtype